version: '3.8'
services:
  subscription:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - subscription_db
      - subscription_db_testing

  subscription_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: subscription
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306

  subscription_db_testing:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: subscription_test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata-testing:/var/lib/mysql
    ports:
      - 33064:3306
